# GitLab CI/CD configuration file

include:
  - component: $CI_SERVER_FQDN/ci-components/scc-code-counter/code-counter@0.1.24
    rules:
      - if: $CI_COMMIT_BRANCH == "main"
    inputs:
      SCCCC_CONTAINER_TAG: 0.1.24
      stage: analyze

stages:
  - build
  - analyze
  - package
  - release

package-job:
  stage: package
  image: ubuntu:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "Packaging productvariantpriceupdate module ..."
    - apt-get update -q && apt-get install -y -q zip && apt-get install -y -q curl
    - mkdir artifacts
    - cp LICENSE.md productvariantpriceupdate/LICENSE.md
    - cp README.md productvariantpriceupdate/README.md
    - cp CHANGELOG.md productvariantpriceupdate/ChangeLog.md
    - 'zip -r "./artifacts/module_productvariantpriceupdate-$CI_COMMIT_TAG.zip" ./productvariantpriceupdate/'
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file "artifacts/module_productvariantpriceupdate-$CI_COMMIT_TAG.zip" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/productvariantpriceupdate/${CI_COMMIT_TAG}/module_productvariantpriceupdate-$CI_COMMIT_TAG.zip"'
    - echo "productvariantpriceupdate module packaged."
  artifacts:
    name: '$CI_JOB_NAME $CI_COMMIT_SHORT_SHA'
    untracked: false
    paths:
      - artifacts/

release_job:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "Running productvariantpriceupdate module release job"
  dependencies:
    - package-job
  release:                               # See https://docs.gitlab.com/ee/ci/yaml/#release for available properties
    tag_name: '$CI_COMMIT_TAG'
    description: 'Release created from CI/CD'
    ref: '$CI_COMMIT_SHA'
    assets:
      links:
        - name: 'module_productvariantpriceupdate-$CI_COMMIT_TAG'
          url: '${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/productvariantpriceupdate/${CI_COMMIT_TAG}/module_productvariantpriceupdate-$CI_COMMIT_TAG.zip'
          link_type: package
